### ISSUE TITLE
добавить страницу ввода параметров иконки

### ISSUE THREAD

**Issue by luxee** [cybearz/CheckPassport#14]
name: PageIconForm \
url: /icons \
ссылка на страницу: из AppBar

2 поля: 
* имя иконки без префикса "mdi-"
* radio-button список цветов из палитры Vuetify по алфавиту

Кнопка "Показать": \
переход на соответствующий PageIcon

**Comment by cybearz** [comment]
Страница добавлена. Однако, еще не придумал, как проверять существует ли иконка с таким именем или нет.

**Comment by luxee** [comment]
не могу найти ссылкУ на PageIconForm (

![image](https://user-images.githubusercontent.com/1793639/133974085-da9d9235-2c36-4f0f-ac12-473202b3cc2b.png)

**Comment by cybearz** [comment]
Добавил
