### ISSUE TITLE
поломался отображение существующей! иконки при вводе url (не через диалог)

### ISSUE THREAD

**Issue by luxee** [cybearz/CheckPassport#18]
![image](https://user-images.githubusercontent.com/1793639/134416309-32c6a6d8-e39a-4988-8bdd-9a1f1db261ef.png)

**Comment by cybearz** [comment]
![image](https://user-images.githubusercontent.com/40028882/134425365-eebc34aa-96ac-4c4b-8c74-45736ecd030a.png)
Исправил

**Comment by luxee** [comment]
увидел твой коммент)
